### ISSUE TITLE
Frankot-Chellapa integration

### ISSUE THREAD

**Issue by lsu-lesbutler** [wavepy/wavepy#13]
The following Matlab code by Prof. Amit Agrawal (U Maryland) was once posted at http://www.umiacs.umd.edu/~aagrawal/software.html
and accessed about July 2014. Today, July, 2016, the site is down.

I've converted the Matlab into Mathematica (below)
********************_Matlab version**_*******************************************
function z = frankotchellappa(dzdx,dzdy)
% Frankt-Chellappa Algrotihm
% Input gx and gy
% Output : reconstruction
% Author: Amit Agrawal, 2005
disp('=======================================================')
disp('Solving Using Frankot Chellappa Algorithm');

if ~all(size(dzdx) == size(dzdy))
    error('Gradient matrices must match');
end
[rows,cols] = size(dzdx);
[wx, wy] = meshgrid(-pi/2:pi/(cols-1):pi/2,-pi/2:pi/(rows-1):pi/2);
% Quadrant shift to put zero frequency at the appropriate edge
wx = ifftshift(wx); wy = ifftshift(wy);
DZDX = fft2(dzdx);   % Fourier transforms of gradients
DZDY = fft2(dzdy);
% Integrate in the frequency domain by phase shifting by pi/2 and
% weighting the Fourier coefficients by their frequencies in x and y and
% then dividing by the squared frequency.  eps is added to the
% denominator to avoid division by 0.
j = sqrt(-1);
dd = wx.^2 + wy.^2;
Z = (-j_wx._DZDX -j_wy._DZDY)./(wx.^2 + wy.^2 + eps); 
z = real(ifft2(Z));  % Reconstruction
z = z - min(z(:));
z = z/2;

*********************_Mathematica version**_******************************************
If[EvenQ[rows],
vectorRows = Drop[N[Range[-[Pi]/2,[Pi]/2,[Pi]/(rows)]],-1],
vectorRows =N[Range[-[Pi]/2,[Pi]/2,[Pi]/(rows-1)]]];
vectorRows=$MachineEpsilon+vectorRows;
If[EvenQ[columns],
vectorColumns = Drop[N[Range[-[Pi]/2,[Pi]/2,[Pi]/(columns)]],-1],
vectorColumns =N[Range[-[Pi]/2,[Pi]/2,[Pi]/(columns-1)]]];
vectorColumns=$MachineEpsilon+vectorColumns;
MatrixForm[wx = ConstantArray[vectorColumns,rows] ];
MatrixForm[wy = Transpose[ConstantArray[vectorRows,columns]]];
MatrixForm[wx=RotateLeft[wx,{0,Ceiling[(columns-1)/2]}]];
MatrixForm[wy=RotateLeft[wy,{Ceiling[(rows-1)/2]}]];
parametersFourier={1,-1};
fftdpcHorizontalUnWrapped  =Fourier[dpcHorizontal,FourierParameters->parametersFourier];
fftdpcVerticalUnWrapped  =Fourier[dpcVertical,FourierParameters->parametersFourier];

numerator = I_wx \* fftdpcVerticalUnWrapped -I_wy*fftdpcHorizontalUnWrapped;
denominator=wx^2 + wy^2;
Z=numerator/denominator;
z = Re[InverseFourier[Z, FourierParameters->parametersFourier]];
z = z-Min[z];
phase2DFrankotChepella = z/2;

climPhase={Min[phase2DFrankotChepella],Max[phase2DFrankotChepella]}
Export[pathFITS<>nameStr<>"_phase_FC"<>".fits",phase2DFrankotChepella,"FITS"];
If[flagGraph,  Module[{},
plotThree= funcPlotSurfaceHist[phase2DFrankotChepella, climPhase,"TemperatureMap",2*10^6,"phi",True] ;
Print[plotThree];
Export[pathFigures<>nameStr<>"_phase2D-FC_surface_hist"<>".png",plotThree,"PNG"] ] ,
Print[ImageAdjust[ImageResize[Image[phase2DFrankotChepella,"Real"],300]]  ]  ]

*********************_Mathematica version**_******************************************

**Comment by wcgrizolli** [comment]
@lsu-lesbutler , You mention in the documents that this integration is tricky. Do you have a explanation for why it is tricky?

I've been working with integration and maybe I have something to contribute. But first I want to know if we are facing the same problems.

**Comment by lsu-lesbutler** [comment]
Hi Walan,
“Tricky” is an understatement.  I have real trouble getting a result with a flat baseline and reasonable values for the phase.

I’ve explored some coding tricks.  This exploration is not logically driven, but rather trying anything to get a reasonable integration.
1) force the dimensionality to be odd.
2) add a machine precision constant to the denominator to prevent divide by zero.

The capital “I” below is Mathematica’s sqrt(-1).

Far below are images from “20160724_Spheres_CBgrating” , 1-st Talbot distance for the big sphere in the lower left corner.  This should have been an ideal test case, but I’ve screwed it up somehow.  The DPC(V) and  DPC(H) are well-behaved with flat background and no phase wrap.  Yet, my FC code gives a weird cloverleaf, and not the expected sphere projection.

Best wishes
Les

**Comment by wcgrizolli** [comment]
I see. Maybe I have an alternative, but first I want to make some points clear.

What exactly do you call "Frankot-Chellapa"? Is it only the equation

![1](https://cloud.githubusercontent.com/assets/20505144/18634521/d31e372a-7e46-11e6-81d2-ecd9742d1289.png)

or does it also refer to some additional method?

**Comment by lsu-lesbutler** [comment]
Hi Walan,
I think Frankot-Chellappa is the name of the 2D integration.    Here are a couple of the oldest papers in X-ray imaging that mention F-C.
Les

**Comment by wcgrizolli** [comment]
Ok. I am asking because the original article of Frankot-Chellapa seems more complex, discussing some requirements for the derivative fuunctions.

**Comment by wcgrizolli** [comment]
I've been studying this method of integration, in particular why it occasionally fails. The discussion is a bit too long to put here, so I included it in the overleaf document "Guidelines[...]".

@lsu-lesbutler could you please check my method and test it in your scripts? It is described in (the current) section 5.13. It should require small changes in the code.

**Comment by lsu-lesbutler** [comment]
Hi Walan,
Yes, I will test your FFT shift in my scripts (a couple of days).  I think you’ve found a reliable solution to the problem.  Is the reciprocal space shift working well in your scripts?
Les

On Sep 20, 2016, at 6:34 PM, Walan Grizolli <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been studying this method of integration, in particular why it occasionally fails. The discussion is a bit too long to put here, so I included it in the overleaf document "Guidelines[...]".

@lsu-lesbutler<https://github.com/lsu-lesbutler> could you please check my method and test it in your scripts? It is described in (the current) section 5.13. It should require small changes in the code.

**Comment by lsu-lesbutler** [comment]
Hi Walan,
I was about to suggest generating synthetic data and trying the reciprocal space shift, but in re-reading your email, I see you have generated test functions.  I presume the test functions showed no sign of the structure seen in the real data.

The structure at  y = -200um doesn’t look like an experimental problem.  If I remember correctly, the crop size for this sphere is around 300x300 which means the structure could be at that magic 256 (2^8) spot. Otherwise, I’m stuck. No suggestions.

Les

On Sep 21, 2016, at 7:08 PM, Walan Grizolli <notifications@github.com<mailto:notifications@github.com>> wrote:


Previously I could not get reasonable results. With the reciprocal space shift it works very well for test functions.

However I still see some problems for real data. For instance see this figure, after using the integration method for speckle tracking data

[figure_1]<https://cloud.githubusercontent.com/assets/20505144/18733178/566645b2-802e-11e6-87c2-a9278ab567c1.png>

There is this strange structure at y = -200um. I have no idea what is that, but it seems to be affected by the number of points (more points, less likely to have this kind structure).

Any ideas?

**Comment by wcgrizolli** [comment]
The code by  Amit Agrawal (as today) is available at:

http://www.cs.cmu.edu/~ILIM/projects/IM/aagrawal/index.html

in the section "What is the Range of Surface Reconstructions from a Gradient Field?"

**Comment by wcgrizolli** [comment]
Interesting article about integration:

http://dx.doi.org/10.1016/j.optlaseng.2014.07.002

**Comment by wcgrizolli** [comment]
This discussion developed mostly offline. The conclusion is that Frankot-Chellapa (FC) is indeed limited, being particularly bad when integrating sharp edges. FC is currently implemented and in use, see:

http://wavepy.readthedocs.io/en/latest/source/api/wavepy.surface_from_grad.html#wavepy.surface_from_grad.frankotchellappa

The padding was a significant improvement, but further improvements in integration means to use a different algorithm. The discussion about different algorithms is done in

https://doi.org/10.1007/11744023_45
and
https://doi.org/10.1109/CVPR.2008.4587414

These algorithms are available as MATLAB code and we are trying to code it in python.

**Comment by wcgrizolli** [comment]
Concerning FC, there is no improvements to be done and this issue must be closed
